# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-10 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='media/avatar/default.svg', upload_to='media/avatar/'),
        ),
    ]
