# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210210_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_up',
            field=models.NullBooleanField(choices=[(1, 'like'), (2, 'dislike')]),
        ),
    ]
