# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-12 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20210212_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='is_up',
            field=models.NullBooleanField(choices=[(True, 'like'), (False, 'dislike')]),
        ),
    ]
