# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-13 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20210212_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_del',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='avatar/default.svg', upload_to='avatar/'),
        ),
    ]
